name: Deploy to Workshop

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    if: github.repository == 'ACF-Team/Ponder'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: project

      - name: Upload to Workshop
        uses: CFC-Servers/gmod-upload@master
        with:
          #id: placeholder
          changelog: "${{ github.event.head_commit.message }}"
          title: "Ponder"
          type: "tool"
          tag1: "build"
          tag2: "fun"
          tag3: "movie"
        env:
          STEAM_USERNAME: ${{ secrets.ACF_STEAM_ACCOUNT }}
          STEAM_PASSWORD: ${{ secrets.ACF_STEAM_PASSWORD }}
